// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAliJKRUQflsjDgfdIioiYTxOFTime0mRo',
    appId: '1:453706001993:web:c9ee25e5c404d93829d998',
    messagingSenderId: '453706001993',
    projectId: 'bluebird-101b8',
    authDomain: 'bluebird-101b8.firebaseapp.com',
    databaseURL: 'https://bluebird-101b8-default-rtdb.firebaseio.com',
    storageBucket: 'bluebird-101b8.firebasestorage.app',
    measurementId: 'G-6KW7MSX4F0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTS4iGNKnNJ1aQJ3weLHCaaOWTrHG2IjI',
    appId: '1:453706001993:android:a002fcca5fc243b429d998',
    messagingSenderId: '453706001993',
    projectId: 'bluebird-101b8',
    databaseURL: 'https://bluebird-101b8-default-rtdb.firebaseio.com',
    storageBucket: 'bluebird-101b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxCP5M0KkiKYEK-E5uaTRamv_iQ7ydhsE',
    appId: '1:453706001993:ios:a7244d6a08786bc629d998',
    messagingSenderId: '453706001993',
    projectId: 'bluebird-101b8',
    databaseURL: 'https://bluebird-101b8-default-rtdb.firebaseio.com',
    storageBucket: 'bluebird-101b8.firebasestorage.app',
    iosClientId: '453706001993-5nbgpu8j5plcnvgf2jmnj3gpjjpij239.apps.googleusercontent.com',
    iosBundleId: 'com.example.bluebirdApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxCP5M0KkiKYEK-E5uaTRamv_iQ7ydhsE',
    appId: '1:453706001993:ios:a7244d6a08786bc629d998',
    messagingSenderId: '453706001993',
    projectId: 'bluebird-101b8',
    databaseURL: 'https://bluebird-101b8-default-rtdb.firebaseio.com',
    storageBucket: 'bluebird-101b8.firebasestorage.app',
    iosClientId: '453706001993-5nbgpu8j5plcnvgf2jmnj3gpjjpij239.apps.googleusercontent.com',
    iosBundleId: 'com.example.bluebirdApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAliJKRUQflsjDgfdIioiYTxOFTime0mRo',
    appId: '1:453706001993:web:8d2ac6833d664a0429d998',
    messagingSenderId: '453706001993',
    projectId: 'bluebird-101b8',
    authDomain: 'bluebird-101b8.firebaseapp.com',
    databaseURL: 'https://bluebird-101b8-default-rtdb.firebaseio.com',
    storageBucket: 'bluebird-101b8.firebasestorage.app',
    measurementId: 'G-KQ94F95VE2',
  );
}
